#!/bin/sh

cat <<\EOF
Hooks: Pulling before commit
EOF

output=$(git pull --recurse-submodules=yes)

if (test $? -ne 0)
then
	echo "Will not commit because an error occured on pull."
fi

if [[ ${output} != *"Already up to date."* ]];then
    # output does not contain Already up to date.
	echo "Will not commit because there is a commit that we didnt pull before."
	exit 1
fi

exit 0

